from database_management.models.Game import Game
from database_management.models.Format import Format
from database_management.models.Card import Card
from database_management.models.Cycle import Cycle
from database_management.models.Face import Face

all_cycles = [
    Cycle(_name="shock_lands",
        _regex=r"\(\{T\}: Add \{[WUBRG]\} or \{[WUBRG]\}\.\) As this land enters, you may pay 2 life. If you don't, it enters tapped\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="check_lands",
        _regex=r"This land enters tapped unless you control an? [A-Z][a-z]* or an? [A-Z][a-z]*\. \{T\}: Add \{[WUBRG]\} or \{[WUBRG]\}\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="reveal_lands",
          _regex=r"As this land enters, you may reveal an? [A-Z][a-z]* or [A-Z][a-z]* card from your hand\. If you don't, this land enters tapped\. \{T\}: Add \{[WUBRG]\} or \{[WUBRG]\}.",
		_official=True,
		_category="undefined"),
    Cycle(_name="filter_lands",
          _regex=r"\{T\}\: Add \{C\}\. \{[WUBRG]\/[WUBRG]\}\, \{T\}\: Add \{[WUBRG]\}\{[WUBRG]\}\, \{[WUBRG]\}\{[WUBRG]\}\, or \{[WUBRG]\}\{[WUBRG]\}\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="bond_lands",
          _regex=r"This land enters tapped unless you have two or more opponents\. \{T\}\: Add \{[WUBRG]\} or \{[WUBRG]\}\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="og_dual_lands",
          _regex=r"\(\{T\}\: Add \{[WUBRG]\} or \{[WUBRG]\}\.\)",
		_official=True,
		_category="undefined"),
    Cycle(_name="horizon_lands",
          _regex=r"\{T\}\, Pay 1 life\: Add \{[WUBRG]\} or \{[WUBRG]\}\. \{1\}\, \{T\}\, Sacrifice this land\: Draw a card\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="verge_lands",
          _regex=r"\{T\}: Add \{[WUBRG]\}\. \{T\}\: Add \{[WUBRG]\}\. Activate only if you control an? [A-Z][a-z]* or an? [A-Z][a-z]*\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="og_filter_lands",
          _regex=r"\{1\}\, \{T\}\: Add \{[WUBRG]\}\{[WUBRG]\}\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="tainted_lands",
          _regex=r"\{T\}\: Add \{C\}\. \{T\}\: Add \{[WUBRG]\} or \{[WUBRG]\}\. Activate only if you control a Swamp\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="tango_lands",
          _regex=r"\(\{T\}\: Add \{[WUBRG]\} or \{[WUBRG]\}\.\) This land enters tapped unless you control two or more basic lands\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="fast_lands",
          _regex=r"This land enters tapped unless you control two or fewer other lands\. \{T\}\: Add \{[WUBRG]\} or \{[WUBRG]\}\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="slow_lands",
          _regex=r"This land enters tapped unless you control two or more other lands\. \{T\}\: Add \{[WUBRG]\} or \{[WUBRG]\}\.",
		_official=True,
		_category="undefined"),
    Cycle(_name="pain_lands",
          _regex=r"\{T\}\: Add \{C\}\. \{T\}\: Add \{[WUBRG]\} or \{[WUBRG]\}\. This land deals 1 damage to you\.",
		_official=True,
		_category="undefined")]