from database_management.models.Game import Game
from database_management.models.Format import Format
from database_management.models.Card import Card
from database_management.models.Cycle import Cycle
from database_management.models.Face import Face


all_formats = [
    Format(_display_name='Standard', _scryfall_name='standard',
           _copies = 4, _deck_size = 60,
           _hard_max = False, _arena = True,
           _mtg_online = True, _paper=True),
    Format(_display_name='Modern', _scryfall_name='modern',
           _copies = 4, _deck_size=60,
           _hard_max=False, _arena=False,
           _mtg_online=True, _paper=True),
    Format(_display_name='Legacy', _scryfall_name='legacy',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=False,
           _mtg_online=True, _paper=True),
    Format(_display_name='Vintage', _scryfall_name='vintage',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=False,
           _mtg_online=True, _paper=True),
    Format(_display_name='EDH', _scryfall_name='commander',
           _copies=1, _deck_size=100,
           _hard_max=True, _arena=False,
           _mtg_online=False, _paper=True),
    Format(_display_name='Limited', _scryfall_name='NA',
           _copies=4, _deck_size=40,
           _hard_max=False, _arena=True,
           _mtg_online=True, _paper=True),
    Format(_display_name='Historic', _scryfall_name='historic',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=True,
           _mtg_online=False, _paper=False),
    Format(_display_name='Timeless', _scryfall_name='timeless',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=True,
           _mtg_online=False, _paper=False),
    Format(_display_name='Gladiator', _scryfall_name='gladiator',
           _copies=1, _deck_size=100,
           _hard_max=True, _arena=True,
           _mtg_online=False, _paper=False),
    Format(_display_name='Pioneer', _scryfall_name='pioneer',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=True,
           _mtg_online=True, _paper=True),
    Format(_display_name='Explorer', _scryfall_name='explorer',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=True,
           _mtg_online=False, _paper=False),
    Format(_display_name='Pauper', _scryfall_name='pauper',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=False,
           _mtg_online=True, _paper=True),
    Format(_display_name='Penny Dreadful', _scryfall_name='penny',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=False,
           _mtg_online=True, _paper=False),
    Format(_display_name='Oathbreaker', _scryfall_name='oathbreaker',
           _copies=1, _deck_size=60,
           _hard_max=True, _arena=False,
           _mtg_online=False, _paper=False),
    Format(_display_name='Standard Brawl', _scryfall_name='standardbrawl',
           _copies=1, _deck_size=60,
           _hard_max=True, _arena=True,
           _mtg_online=True, _paper=False),
    Format(_display_name='Brawl', _scryfall_name='brawl',
           _copies=1, _deck_size=60,
           _hard_max=True, _arena=True,
           _mtg_online=True, _paper=False),
    Format(_display_name='Alchemy', _scryfall_name='alchemy',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=True,
           _mtg_online=False, _paper=False),
    Format(_display_name='Pauper Commander', _scryfall_name='paupercommander',
           _copies=1, _deck_size=100,
           _hard_max=True, _arena=False,
           _mtg_online=False, _paper=False),
    Format(_display_name='Duel Commander', _scryfall_name='duel',
           _copies=1, _deck_size=100,
           _hard_max=True, _arena=False,
           _mtg_online=False, _paper=False),
    Format(_display_name='Old School', _scryfall_name='oldschool',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=False,
           _mtg_online=False, _paper=False),
    Format(_display_name='Pre-Modern', _scryfall_name='premodern',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=False,
           _mtg_online=False, _paper=False),
    Format(_display_name='Pre-EDH', _scryfall_name='predh',
           _copies=1, _deck_size=100,
           _hard_max=True, _arena=False,
           _mtg_online=False, _paper=False),
    Format(_display_name="Future Standard", _scryfall_name='future',
           _copies=4, _deck_size=60,
           _hard_max=False, _arena=False,
           _mtg_online=False, _paper=False)
    ]


